"""Compatibility exports for the JianerCore plugin loader."""

from .plugins import (
    BUILTIN_PLUGINS,
    DISABLED_PREFIX,
    INCOMPATIBLE_IN_FEISHU,
    PLUGIN_EXTENSIONS,
    PLUGIN_FOLDER,
    PLUGIN_NAME_PATTERN,
    PLUGIN_NAME_PREFIX,
    RESERVED_PLUGIN_NAMES,
    LoadResult,
    Plugin,
    PluginManager,
    PluginManagerState,
    PluginMetadata,
    PluginSetupError,
    ShutdownReport,
    SubscriptionOwner,
    SubscriptionToken,
    is_valid_plugin_name,
    load_plugins,
)

__all__ = [
    "BUILTIN_PLUGINS",
    "DISABLED_PREFIX",
    "INCOMPATIBLE_IN_FEISHU",
    "PLUGIN_EXTENSIONS",
    "PLUGIN_FOLDER",
    "PLUGIN_NAME_PATTERN",
    "PLUGIN_NAME_PREFIX",
    "RESERVED_PLUGIN_NAMES",
    "LoadResult",
    "Plugin",
    "PluginManager",
    "PluginManagerState",
    "PluginMetadata",
    "PluginSetupError",
    "ShutdownReport",
    "SubscriptionOwner",
    "SubscriptionToken",
    "is_valid_plugin_name",
    "load_plugins",
]
